config/routes.rb
Rails.application.routes.draw do
  resources :starships
  get 'admin/hacker_list'
  get 'starships/create_your_own_starship'

  devise_for :admins
  devise_for :hackers
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crew_member.rb
class CrewMember < ApplicationRecord
	belongs_to :starship
end

app/models/hacker.rb
class Hacker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/starship.rb
class Starship < ApplicationRecord
	has_many :crew_members

	accepts_nested_attributes_for :crew_members, reject_if: lambda  { |attributes| attributes["name"].blank?}

	validates_presence_of :name
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def hacker_list
  	authenticate_admin!
  	@hackers = Hacker.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  before_action :set_starship, only: [:show, :edit, :update, :destroy]

  # GET /starships
  # GET /starships.json
  def index
    @starships = Starship.all
  end

  # GET /starships/1
  # GET /starships/1.json
  def show
  end

  # GET /starships/new
  def new
    @starship = Starship.new
    3.times { @starship.crew_members.build }
  end

  # GET /starships/1/edit
  def edit
  end

  # POST /starships
  # POST /starships.json
  def create
    @starship = Starship.new(starship_params)

    respond_to do |format|
      if @starship.save
        StarshipMailer.starship_created_mailer(@starship).deliver_now
        format.html { redirect_to @starship, notice: 'Starship was successfully created.' }
        format.json { render :show, status: :created, location: @starship }
      else
        format.html { render :new }
        format.json { render json: @starship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /starships/1
  # PATCH/PUT /starships/1.json
  def update
    respond_to do |format|
      if @starship.update(starship_params)
        format.html { redirect_to @starship, notice: 'Starship was successfully updated.' }
        format.json { render :show, status: :ok, location: @starship }
      else
        format.html { render :edit }
        format.json { render json: @starship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /starships/1
  # DELETE /starships/1.json
  def destroy
    @starship.destroy
    respond_to do |format|
      format.html { redirect_to starships_url, notice: 'Starship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_your_own_starship
    redirect_to new_starship_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_starship
      @starship = Starship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def starship_params
      params.require(:starship).permit(:name, :email, crew_members_attributes: [:starship_id, :name, :division])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/starships_helper.rb
module StarshipsHelper
end

app/views/admin/hacker_list.html.erb
<h1>Hacker List</h1>
<thead>
	<th>Email</th>
	<th>Join Date</th>
</thead>
<tbody>
	<% @hackers.each do |hacker| %>
		<tr><%= hacker.email %></tr>
		<tr><%= hacker.created_at.to_date %></tr>
	<% end %>
</tbody>

app/views/home/index.html.erb
<h1>Welcome to My Site!</h1>
<p><button id="modal-link">Kirk Quote</button></p>
<div id="modal-background">
	<div id="modal-window">
		<p class="modal-text">Beam me up, Scotty!</p>
		<a href="#" class="close">Close</a>
	</div>
</div>

<script>
	$(document).ready(function() {
		$("#modal-link").click(function() {
			$("#modal-background").fadeIn();
		});

		$(".close").click(function() {
			$("#modal-background").fadeOut();
		})
	})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRailsExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>
  	<%= link_to 'Sign in', new_hacker_session_path %>
    <%= link_to 'Sign out', destroy_hacker_session_path, method: :delete %>
  	<%= link_to 'Sign up', new_hacker_registration_path %>
    <%= link_to 'Admin Sign in', new_admin_session_path %>
    <%= link_to 'Admin Sign out', destroy_admin_session_path, method: :delete %>
    <% if admin_signed_in? %>
      <%= link_to 'View Hacker List', admin_hacker_list_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/starships/_form.html.erb
<%= form_with(model: starship, local: true) do |form| %>
  <% if starship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(starship.errors.count, "error") %> prohibited this starship from being saved:</h2>

      <ul>
      <% starship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :starship_name %>
  </div>
  
  Crew Members:
  <ul>
    <%= form.fields_for :crew_members do |crew| %>
      <li>
        <%= crew.label :name %>
        <%= crew.text_field :name %>
        <%= crew.label :division %>
        <%= crew.select(:division, ["Command", "Engineering", "Science"]) %>
      </li>
    <% end %>
  </ul>
  Enter your email to receive the awesome stuff!
  <div class="field">
    <%= form.label :email %>
    <br>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/starships/edit.html.erb
<h1>Editing Starship</h1>

<%= render 'form', starship: @starship %>

<%= link_to 'Show', @starship %> |
<%= link_to 'Back', starships_path %>

app/views/starships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Starships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @starships.each do |starship| %>
      <tr>
        <td><%= starship.name %></td>
        <td><%= link_to 'Show', starship %></td>
        <td><%= link_to 'Edit', edit_starship_path(starship) %></td>
        <td><%= link_to 'Destroy', starship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Starship', new_starship_path %>

app/views/starships/new.html.erb
<h1>New Starship</h1>

<%= render 'form', starship: @starship %>

<%= link_to 'Back', starships_path %>

app/views/starships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @starship.name %>
  <strong>Crew Members:</strong>
	<% @starship.crew_members.each do |crew_member| %>
		<%= crew_member.name %>
	<% end %>
</p>

<%= link_to 'Edit', edit_starship_path(@starship) %> |
<%= link_to 'Back', starships_path %>